### ISSUE TITLE
[FEA] Add option to select between Struct of Arrays vs Array of Structs

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cuCollections#103]
**Is your feature request related to a problem? Please describe.**

All of the current hash map implementations use an Array of Structs storage implementation. 

There are instances where it could be nice to have a Struct of Arrays layout.

**Describe the solution you'd like**

Provide some way to configure the storage layout. Probably via some template parameter. 

We'd want to avoid as much duplication as possible between the AoS vs SoA implementations, so would require some clever abstraction.

**Comment by sleeepyjack** [comment]
Something like this: https://github.com/sleeepyjack/warpcore/blob/ba5a6a84a8797464e2ce8dd03b269907ee70e7c2/include/warpcore/storage.cuh#L150

**Comment by PointKernel** [comment]
Future work tracked via #206
