### ISSUE TITLE
[FEA] Add an overload for `insert` that returns the inserted (or existing) value 

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cuCollections#111]
**Is your feature request related to a problem? Please describe.**

Given a set of keys and values, either insert the key/value if doesn't exist, otherwise, return the existing value.

**Comment by jrhemstad** [comment]
On further consideration, I don't think this needs to be a separate function, but can just be another overload of `insert` that takes an output iterator:

```
  template <typename InputIt,
            typename OutputIt
            typename Hash,
            typename KeyEqual>
  void insert(InputIt first, InputIt last, OutputIt output_first, Hash hash = Hash{}, KeyEqual key_equal = KeyEqual{});`
```

`*(output_first+i)` would equal `(first+i)->second` if `(first+i)->first` was not present in the map, otherwise, it will equal the value that was already present in the map associated with that key. 

We should probably require that `iterator_traits<OutputIt>::value_type` be a `pair<T, bool>` to indicate if each key was inserted or not.

**Comment by PointKernel** [comment]
surpassed by #477
