### ISSUE TITLE
[BUG] Static map example doesn't compile

### ISSUE THREAD

**Issue by akifcorduk** [NVIDIA/cuCollections#123]
In the static map example, the constructor of `cuco::static_map` have `cudaStream_t` as last argument, but this doesn't compile, The constructor should be called without `cudaStream_t`.

**Comment by jrhemstad** [comment]
Thanks for the issue. We'll try and get this remedied ASAP as well as tackle https://github.com/NVIDIA/cuCollections/issues/124 to make sure it doesn't happen again!

**Comment by PointKernel** [comment]
I've pulled the latest `dev` branch and it builds just fine. @akifcorduk Can you please provide more details about the error i.e. how to reproduce it?

**Comment by akifcorduk** [comment]
The code in the `dev` branch seems to have the correct constructor. We are using `rapidsai/raft` and `cuco` comes as a dependency of it. https://github.com/rapidsai/raft/blob/branch-22.02/cpp/cmake/thirdparty/get_cuco.cmake here it is using a non-existent tag so I don't know which version it is cloning. It seems there is a problem with our build system. I think we can close this since it is probably a cmake issue on our side.

**Comment by PointKernel** [comment]
Thanks for the info. `rapidsai/raft` fetches this [commit](https://github.com/NVIDIA/cuCollections/commit/f0eecb203590f1f4ac4a9f1700229f4434ac64dc). Updating the tag to the latest commit (`76a6ba1d08761f7e14f27c6794ca2d469301b54f`) will solve the issue IMO. Please let us know if works.

**Comment by akifcorduk** [comment]
Thanks! That's solved the problem.
