### ISSUE TITLE
[FEA] Use `sentinel` namespace in all applicable map types

### ISSUE THREAD

**Issue by PointKernel** [NVIDIA/cuCollections#162]
**Is your feature request related to a problem? Please describe.**
`sentinel` namespace has been added in #142 , which provides a wrapper around sentinel values. Currently, this namespace is only applied in `cuco::static_map`.

**Describe the solution you'd like**
Use `sentinel` namespace consistently across all applicable map types.

**Comment by m3g4d1v3r** [comment]
Hello PointKernel!
Is https://github.com/NVIDIA/cuCollections/pull/163 a good approach for this issue? Maybe I'm forgetting something...
