### ISSUE TITLE
[FEA] Support `pair_contains` in `static_map` and `static_multimap`

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/cuCollections#173]
In `static_multimap`, there are various `pair_*` APIs but not `pair_contains`. Sometimes we need it for checking the existence of key/value pairs given from input iterators.

It's great to have such API added to `static_multimap` as well as `static_map`.

**Comment by PointKernel** [comment]
Closing this since the functionality is no longer desired by using set `contains`.
