### ISSUE TITLE
[FEA] Support `pair_contains_if` in `static_map` and `static_multimap`

### ISSUE THREAD

**Issue by ttnghia** [NVIDIA/cuCollections#176]
Once we have `pair_contains` (https://github.com/NVIDIA/cuCollections/issues/173), we also need to have `pair_contains_if` so we can avoid checking contains for the elements that we already knew the result for them. By doing so, we will not perform unnecessarily expensive computations.

**Comment by PointKernel** [comment]
Closing this since the functionality is no longer desired by using set `contains_if`.
