### ISSUE TITLE
[FEA] Add Windows support

### ISSUE THREAD

**Issue by PointKernel** [NVIDIA/cuCollections#195]
**Is your feature request related to a problem? Please describe.**
The current cuCollections doesn't support building on Windows and we should support this.

**Comment by sleeepyjack** [comment]
As @jrhemstad mentioned earlier, setting up a CI for this would not be fun.

**Comment by realhaik** [comment]
@sleeepyjack Hey friend, do your mangers know that you have decided not to support windows because it is "not fun"?

**Comment by PointKernel** [comment]
> @sleeepyjack Hey friend, do your managers know that you have decided not to support windows because it is "not fun"?

We appreciate feedback from our community, but it's important to keep discussions respectful and constructive. The question above isn't helpful and doesn't contribute to solving the issue.

If you’re interested in exploring how to compile and run it on Windows, we’d be more than happy to offer support.

**Comment by sleeepyjack** [comment]
@realhaik Yes, they are.

Windows platforms are already supported through WSL, which is also the preferred option for most users who utilize GPU-accelerated libraries on Windows systems.
Hence, we deprioritized native Windows support, given that the required code change and the associated number of dev hours would be significant compared to the number of users asking for this feature.
If WSL is not an option for you, we would like to encourage you to send a PR implementing native support.

**Comment by realhaik** [comment]
@sleeepyjack I am not a C++ programmer, so no point in assigning this to me. What I do know is that what you are saying is complete BS. WSL has nothing to do with development, in my Visual Studio 2022 I can't reference the cuColections, and can't build/run a project that includes the cuColections.

**Comment by sleeepyjack** [comment]
> WSL has nothing to do with development

Lol. You got to be kidding me.
https://learn.microsoft.com/en-us/cpp/build/walkthrough-build-debug-wsl2?view=msvc-170

I'd suggest you use some of that toxic energy to read through this tutorial.

**Comment by realhaik** [comment]
@sleeepyjack For some reason I think that you did not use this WSL thing yourself, before recommending it to others. 
I can tell you that this thing is fake junk, it does not really work. I have spent past 3 weeks, 8 hours a day trying to get this working, but your cuCollection lib refuses to work there. 

Also I can tell you that the cuCollection lib code is a real trash, you have no clue on how to ship software. It is VERY obvious that you couldn’t care less about the users that are going to use the cuCollection code.
But I don't blame you, your managers are the ones that are responsible for this disgrace.

**Comment by PointKernel** [comment]
Updates: Building cuCollections in WSL is pretty straightforward. Once CUDA and a relatively new CMake are installed, all examples, benchmarks and unit tests can build and run flawlessly.

Note: the whole process from installing WSL from scratch to CUDA and CMake installation and running tests took about 30 minutes.

Closing this and will track the native building with MSVC in a separate issue.
