### ISSUE TITLE
[BUG] `static_map::device_mutable_view::insert` should return iterator to inserted / existing element

### ISSUE THREAD

**Issue by hahnjo** [NVIDIA/cuCollections#200]
**Describe the bug**
Commit https://github.com/NVIDIA/cuCollections/commit/0145753a5531aade683326981d98196aa8a56bac changed `insert` to only return a `bool`.

**Expected behavior**
The long form of the documentation still says:
https://github.com/NVIDIA/cuCollections/blob/e91e9dabc9d2855a70446de9b3f9ee6208220be5/include/cuco/static_map.cuh#L925-L927
This is required to implement insert-or-update access; right now a kernel would need both a (non-mutable) `device_view` to call `find` and a `device_mutable_view` to call `insert`. I'm not even sure if using the former in parallel with insertions is even safe?

**Additional context**
`std::unordered_map` provides the same semantics of returning an iterator with `insert`.

**Comment by PointKernel** [comment]
Related to #111.

> I'm not even sure if using the former in parallel with insertions is even safe?

Concurrent insert/find is allowed if `supports_concurrent_insert_find()` is true.

**Comment by hahnjo** [comment]
> Related to #111.

I disagree: That issue is about the host bulk API, I'm interested in the device API.

**Comment by PointKernel** [comment]
> That issue is about the host bulk API

Right, the host bulk implementation invokes the corresponding device function internally. By all means, we will add an overload returning existing elements for both host and device `insert`

**Comment by hahnjo** [comment]
I don't think you can overload based on the return type; this needs to change the interface to match the documentation...

**Comment by jrhemstad** [comment]
The documentation is out of date. It _used_ to return an iterator, but we discovered that could lead to race conditions in scenarios where the insertion does not happen fully atomically. 

These conditions are a function of the data types and the architecture one is compiling for. We could conceivably detect that scenario and use `enable_if` to select between two overloads of `insert`, but that would be quite confusing to have the return value of `insert` have very different semantics based on the key/value type and architecture. 

Alternatively, we could add a new `insert`-like function that returns an iterator that is only enabled in scenarios where returning an iterator is safe.

**Comment by sleeepyjack** [comment]
> Alternatively, we could add a new insert-like function that returns an iterator that is only enabled in scenarios where returning an iterator is safe.

How about `fetch_insert` following the similar semantics of atomic operations?

**Comment by hahnjo** [comment]
@jrhemstad 

> The documentation is out of date. It _used_ to return an iterator, but we discovered that could lead to race conditions in scenarios where the insertion does not happen fully atomically.

Hm, could you elaborate on that? I had a quick look at the implementation of `insert` and couldn't spot anything suspicious. Is it because, in the case the value is not packable, it uses two `compare_exchange_strong` with `memory_order_relaxed`? Depending on how weak the GPU memory model is, this *could* mean that the value is not visible (yet) to a plain load even if the written key is. IIRC `memory_order_acquire` and `_release` are only available with later architectures?

> > Alternatively, we could add a new insert-like function that returns an iterator that is only enabled in scenarios where returning an iterator is safe.
> 
> How about `fetch_insert` following the similar semantics of atomic operations?

:+1: for the name if this functionality cannot be reliably provided by `insert` (see above) or requires stronger memory ordering.

**Comment by jrhemstad** [comment]
> Is it because, in the case the value is not packable, it uses two compare_exchange_strong

This is it exactly. There are cases where the key/value are not updated in a single atomic transaction. The `memory_order` is orthogonal. 

You can see here that depending on the key/value type and architecture, `insert` will use one of 3 different methods:
1. If the key/value type are "packable" then we can CAS the entire slot at once
2. If they are not packable, and we are on pre-Volta architecture, then we do a CAS of the key with a normal store of the payload
3. If they are not packable, and on Volta+, we do a "back-to-back" CAS where we do the key and value as distinct CAS operations.

https://github.com/NVIDIA/cuCollections/blob/d6ba69b1fdab90ae144301e77eb93a2f130ede1d/include/cuco/detail/static_map.inl#L457-L468

For both 2&3 it is unsafe to return an iterator because you may return a reference to a slot that is in an undefined state as the key may have been updated but not the value (or vice versa).

It is only safe to return an iterator in 1, when the key/value are updated as a single atomic transaction.

**Comment by hahnjo** [comment]
> For both 2&3 it is unsafe to return an iterator because you may return a reference to a slot that is in an undefined state as the key may have been updated but not the value

Ah thanks, now I understand: During parallel `insert`, the call that actually inserts might not yet have written the value before the duplicate call(s) return. This *could* be solved by spin-waiting for the slot value to be different from the empty sentinel value. That might be naive, but locally seems to work for `cas_dependent_write`.

> (or vice versa).

The only way I can see this happen is via `back_to_back_cas` where one thread is successful for the key and the other is successful for the value. As far as I can see, the function attempts to write the value independently of whether the thread got the key. Is this required for correctness or done for performance reasons? If the latter, it would be feasible to implement `fetch_insert` with only `cas_dependent_write` as fallback, and the user has to "pay" for the additional functionality.

**Comment by jrhemstad** [comment]
> The only way I can see this happen is via back_to_back_cas where one thread is successful for the key and the other is successful for the value. As far as I can see, the function attempts to write the value independently of whether the thread got the key.

Yep, exactly.

>  Is this required for correctness or done for performance reasons?

The `back_to_back_cas` is a performance optimization over `cas_dependent_write`.

There are temporal locality benefits to speculatively issuing the CAS for both the key and value at the same time compared to waiting for the result of the key CAS before storing the value. 

> If the latter, it would be feasible to implement fetch_insert with only cas_dependent_write as fallback, and the user has to "pay" for the additional functionality.

`fetch_insert` would only be safe when `packed_cas` is used.

**Comment by hahnjo** [comment]
> > If the latter, it would be feasible to implement fetch_insert with only cas_dependent_write as fallback, and the user has to "pay" for the additional functionality.
> 
> `fetch_insert` would only be safe when `packed_cas` is used.

Even if we "enhance" the fallback path via `cas_dependent_write` to make sure that the entire `insert` operation is done? I'll try to prepare draft PR tomorrow so we can discuss based on code...

**Comment by jrhemstad** [comment]
> Even if we "enhance" the fallback path via cas_dependent_write to make sure that the entire insert operation is done?

That wouldn't be safe.

Imagine `t0` and `t1` attempt concurrently insert the values `v0` and `v1` for the same key `k` via `cas_dependent_write`.

If `k` maps to slot `s`, then `t0` and `t1` concurrently CAS `s.first`.

Imagine `t0` wins and writes `v0` to `s.second`.

On `t1` the CAS fails and sees that another thread inserted the same key `k`. Therefore it immediately returns an iterator to to `s`. 

If `t1` attempts to read the value of `s.second`, it is undefined because the write to `s.second` from `t0` may not have happened yet.

**Comment by hahnjo** [comment]
> > Even if we "enhance" the fallback path via cas_dependent_write to make sure that the entire insert operation is done?
> 
> That wouldn't be safe.
> 
> Imagine `t0` and `t1` attempt concurrently insert the values `v0` and `v1` for the same key `k` via `cas_dependent_write`.
> 
> If `k` maps to slot `s`, then `t0` and `t1` concurrently CAS `s.first`.
> 
> Imagine `t0` wins and writes `v0` to `s.second`.
> 
> On `t1` the CAS fails and sees that another thread inserted the same key `k`. Therefore it immediately returns an iterator to to `s`.
> 
> If `t1` attempts to read the value of `s.second`, it is undefined because the write to `s.second` from `t0` may not have happened yet.

Yes, this is the case we need to handle. But I think that's doable (with some extra work) in the `fetch_insert` function. See https://github.com/NVIDIA/cuCollections/pull/202 for an implementation that at least passes the test that I had in mind.
