### ISSUE TITLE
[FEA] Implement `__device__ equal_range(…)`

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#209]
**Is your feature request related to a problem? Please describe.**
User-defined equality operators allow for defining equivalence relations over the key domain, where more than one compared key may map to `true`. This implies, that there may be multiple matching keys satisfying this equivalency for a given input key in a map. For `static_(reduction_}map`, retrieving all matching slots is not possible, since `find`, which follows the interface of `std::map`, will only return the first matching key.

**Describe the solution you'd like**
Implement a device-side function similar to `std::map::equal_range` returning all the slots that are equivalent to a given input key.

**Describe alternatives you've considered**
Implement the same function for the host (bulk) API. However, this might be difficult, since the number of matching slots per input key is not known in advance and thus the position of a output value in the output array is not determined.

**Additional context**
[`std::map::find`](https://en.cppreference.com/w/cpp/container/map/find)
[`std::map::equal_range`](https://en.cppreference.com/w/cpp/container/map/equal_range)

**Comment by jrhemstad** [comment]
> Implement a device-side function similar to std::map::equal_range

What if we instead do something like a device-side `for_each(Key k, F f)`? That is, it applies `f` to every key equivalent to `k`?

Would there be any performance advantages to doing it that way instead of needing to build the iterator facade over the potentially non-contiguous equivalent keys?

**Comment by sleeepyjack** [comment]
> needing to build the iterator facade over the potentially non-contiguous equivalent keys

Yeah, I agree. Implementing such a facade would not be fun.
A `for_each` is a versatile construct that not only solves this problem but has a broad range of applications. We should go with that.

Closing this issue then in favor of #210.
