### ISSUE TITLE
[FEA] Batched reduce_by_key benchmark for dynamic hash map 

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cuCollections#22]
**Is your feature request related to a problem? Please describe.**

Similar to the [reduce by key benchmark for the static map](https://github.com/rapidsai/cuCollectionsInternal/blob/dev/benchmarks/reduce_by_key/reduce_by_key.cu), it would be nice to have a similar benchmark for the dynamic map to showcase a problem that they dynamic map can solve.

The idea would be to emulate a "streaming" workload where you are processing data in batches and building up a single reduce by key result among all of the batches processed thus far. A dynamic map is perfect for this scenario as you may not know how many batches, nor the size of each batch that will be processed. 

So the benchmark would generate batches of key/value pairs and then perform a bulk `insert_reduce_by_key` operation for each batch.

**Comment by PointKernel** [comment]
The reduce by key operation can be done via the `insert_or_apply` API in static map.

Closing this as the original reduce by key benchmark with static map has been deprecated
