### ISSUE TITLE
Typo in docs for dynamic map

### ISSUE THREAD

**Issue by esoha-nvidia** [NVIDIA/cuCollections#231]
https://github.com/NVIDIA/cuCollections/blob/01aa7247a7c8a72e3c808162ca9ad52adb297d4f/include/cuco/dynamic_map.cuh#L61

The dynamic map code has a typo in it.  There's is an `l` missing in `sentinel`.

Even when this is fixed, the code will likely not work because the input type to the `dynamic_map` constructor ought to be a `sentinel` and not just an `int`, right?

This compiles for me:

```cuda
  cuco::sentinel::empty_key<int> empty_key(-1);
  cuco::sentinel::empty_value<int> empty_value(-1);
  cuco::dynamic_map<int, int> m(size_t(100'000), empty_key, empty_value);
```

**Comment by PointKernel** [comment]
Thanks for reporting the issue. You are right, the doc is out of date. 

I will make a PR to fix this.
