### ISSUE TITLE
[ENHANCEMENT]: CRTP/mixins to encode concurrent device-side operations

### ISSUE THREAD

**Issue by PointKernel** [NVIDIA/cuCollections#239]
### Is your feature request related to a problem? Please describe.

```cpp
static_set_ref<insert,contains> map{...};

template <typename Mixins...>
struct static_set_ref : Mixins<static_set_ref>... {};
```
An individual mix-in type would need to query what other types are present in `Mixins...` and then statically dispatch to the appropriate implementation. E.g., `insert` for 8B/8B would use back2back CAS vs cas_dependent_write vs cast_dependent_write_spin depending on whether or not `find` or `insert_and_find` are present in the `Mixins...` pack. 

### Describe the solution you'd like

https://godbolt.org/z/EPvc3Ps88 (example of `static_set_ref`)
https://godbolt.org/z/enW78nP7a (simple mixin example)
https://godbolt.org/z/Mv9W7ooYf (Customizing behavior based on different mixin combinations)
https://godbolt.org/z/srGnPEb7c (Customizing behavior based on different mixin combinations, simpler version)

TODO:

- [ ] non-type template mixin where operators are a `enum class, e.g.
```cpp
enum class operator : int32_t {
  NONE = 0,
  INSERT,
  CONTAINS,
  ...
};
```

### Additional context

References:

https://www.modernescpp.com/index.php/mixins
https://www.fluentcpp.com/2017/12/12/mixin-classes-yang-crtp/
https://stackoverflow.com/questions/26486456/two-different-mixin-patterns-in-c-mixin-crtp

**Comment by sleeepyjack** [comment]
Solved by #246
