### ISSUE TITLE
CUCO_CUDA_MINIMUM_ARCH not correctly expanded when building with CUDA 11.4.0-11.4.4.

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#245]
There seems too be an issue when building with CUDA 11.4.0-11.4.4.
Here is a reproducer: https://godbolt.org/z/YsbTM8GPd

_Originally posted by @sleeepyjack in https://github.com/NVIDIA/cuCollections/discussions/244#discussioncomment-4145867_

**Comment by sleeepyjack** [comment]
I also noticed, that since we switched to `NV_IF_TARGET`, we somehow lost support for CUDA <11.4.0 in godbolt: https://godbolt.org/z/Kj3zW56Eh
I this because the build is picking up the libcu++ version that is included in the CTK, which is too old?

**Comment by PointKernel** [comment]
`<nv/target>` was introduced in [libcu++ 1.5.0](https://github.com/NVIDIA/libcudacxx/releases/tag/1.5.0) (CTK 11.4) so it doesn't work with earlier CTK versions. :disappointed: 

The effort to support pre CUDA-11.5 seems unnecessary to me. We could update the [requirements](https://github.com/NVIDIA/cuCollections#requirements) to `nvcc 11.5.0`.

cc @jrhemstad

**Comment by sleeepyjack** [comment]
> `<nv/target>` was introduced in [libcu++ 1.5.0](https://github.com/NVIDIA/libcudacxx/releases/tag/1.5.0) (CTK 11.4) so it doesn't work with earlier CTK versions. 😞
> 
> The effort to support pre CUDA-11.5 seems unnecessary to me. We could update the [requirements](https://github.com/NVIDIA/cuCollections#requirements) to `nvcc 11.5.0`.

The problem is not only the absence of `<nv/target>` (we only use it to conveniently retrieve the first arg of a macro list) but additionally said list of GPU architectures ([`__CUDA_ARCH_LIST__`](https://docs.nvidia.com/cuda/archive/11.5.0/cuda-compiler-driver-nvcc/index.html#virtual-architecture-macros)) is only available from CUDA 11.5 onwards. 

So yes, I agree, it would be best to drop the support for CUDA <11.5 IMO.

**Comment by jrhemstad** [comment]
What do we use `__CUDA_ARCH_LIST__` for in cuco?

**Comment by jrhemstad** [comment]
Also, there is no reason to tie CTK support version to libcu++ version.  You can get a newer version of libcu++ from GitHub than what is in your CTK. cuco's cmake config will even do it for you via CPM.

**Comment by sleeepyjack** [comment]
> What do we use `__CUDA_ARCH_LIST__` for in cuco? 

since this list is sorted, we can use it to find the minimum arch by extracting the first element. We currently use this to determine if we are running on Volta+ architectures only.

https://github.com/NVIDIA/cuCollections/blob/2a194c9831324904120113bc18135e7933369ee8/include/cuco/detail/__config#L22

**Comment by PointKernel** [comment]
> there is no reason to tie CTK support version to libcu++ version.

Totally agreed. 

Sorry, I wasn't clear. What I wanted to bring up is the fact that users may not know the relationship/dependency between CTK and libcu++. So to solve issues like https://github.com/NVIDIA/cuCollections/discussions/244, changing the compiler to nvcc-11.5+ is a much simpler solution compared to asking them to install a newer version of libcu++ on their own.

**Comment by sleeepyjack** [comment]
But why does the missing `<nv/target>` problem show up on godbolt? Is it just including the headers instead of configuring the project using cmake, i.e. pulling in the dependencies?

**Comment by PointKernel** [comment]
The `<nv/target>` header doesn't exist in [libcu++ 1.4.0](https://github.com/NVIDIA/libcudacxx/releases/tag/1.4.0) (or CTK 11.3) or earlier

**Comment by sleeepyjack** [comment]
Yeah but if cuco is configured using cmake it will pull in whatever libcu++ version we have specified which should be newer than whatever the CTK provides. If however godbolt only includes the headers, then it will fall back to the CTKs libcu++ version.

**Comment by jrhemstad** [comment]
>  If however godbolt only includes the headers, then it will fall back to the CTKs libcu++ version.

Hm, yeah, that's actually a good point. We'd need to update how cuco is added to CE to get it to pull in the appropriate libcu++ dependency as well. Looking at the [docs ](https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md#adding-a-new-library-to-the-live-site) it looks like there's a way to define the library such that it will run the cmake build (which is what we'd want to have CPM fetch the version of libcu++ that we want). 

We'd want to modify that here: https://github.com/compiler-explorer/infra/blob/269d4fd0f85aacb2a2ec86fb4355989130f5d7c6/bin/yaml/libraries.yaml#L1724

**Comment by jrhemstad** [comment]
> What I wanted to bring up is the fact that users may not know the relationship/dependency between CTK and libcu++. So to solve issues like #244, changing the compiler to nvcc-11.5+ is a much simpler solution compared to asking them to install a newer version of libcu++ on their own.

The simpler solution is that they should just use cmake which will fetch the appropriate new version of libcu++ for them.

**Comment by sleeepyjack** [comment]
One major problem with the idea of dropping support for CTK <11.5 is that libcudf still supports 11.0. Dunno if we can convince them to update their requirements.

If you guys have ideas on how to determine the minimum CUDA arch without using `__CUDA_ARCH_LIST__` I'm very open to it but I think we had a lot of discussions in the associated PR already.

In fact, since the build is currently broken for CTK <11.5 and none of the cudf folks is complaining tells me that no one is using such an outdated CTK version in production anymore 😅

**Comment by jrhemstad** [comment]
> that libcudf still supports 11.0.

It supports _running_ alongside a 11.0 cudart, but it requires compiling with nvcc 11.5. 

> If you guys have ideas on how to determine the minimum CUDA arch

Remind me why we need to do this?

**Comment by sleeepyjack** [comment]
> It supports running alongside a 11.0 cudart, but it requires compiling with nvcc 11.5.

I see. In this case my point is invalid.

> Remind me why we need to do this?

https://github.com/NVIDIA/cuCollections/blob/2a194c9831324904120113bc18135e7933369ee8/include/cuco/static_map.cuh#L156-L161
The above snippet is used to check if large types are supported.
`CUCO_HAS_INDEPENDENT_THREADS` is true iff there is no CUDA architecture <700 in the `__CUDA_ARCH_LIST__`:

https://github.com/NVIDIA/cuCollections/blob/dev/include/cuco/detail/__config#L32-L34

**Comment by sleeepyjack** [comment]
Oh, I totally forgot to mention that we could remove this weird `__CUDA_ARCH_LIST__` workaround entirely and switch to `__CUDA_MININUM_ARCH__` once NVIDIA/libcudacxx#296 is resolved.
