### ISSUE TITLE
[FEA] static_map::erase

### ISSUE THREAD

**Issue by Nicolas-Iskos** [NVIDIA/cuCollections#27]
It would be useful to have an `static_map::erase` function to form a more complete API for `static_map`. Perhaps the simplest way to achieve this would be to use a "tombstone" sentinel value to indicate whether or not a slot contains an element that has been deleted. Another option would be to use an array of 1B `atomic<state>` for each slot. The lower 2 bits of this byte could be used to hold states such as `empty`, `filling`, `filled`, or `deleted`.

**Comment by PointKernel** [comment]
Closed via https://github.com/NVIDIA/cuCollections/pull/142
