### ISSUE TITLE
[FEA] Support for non-arithmetic keys

### ISSUE THREAD

**Issue by Nicolas-Iskos** [NVIDIA/cuCollections#28]
When inserting a key into an empty slot, `insert` uses `compare_exchange_strong`, which uses a bitwise equality check between `empty_key_sentinel` and the contents of the slot. Consequently, `find` must also use a bitwise equality check between `empty_key_sentinel` and the contents of the slot when this comparison is performed. This check can be performed using `operator==` for arithmetic types, but a custom high performance `key_equal` function is needed to support the bitwise equality check for all types, including non-arithmetic types.

**Comment by jrhemstad** [comment]
Resolved by https://github.com/NVIDIA/cuCollections/pull/79
