### ISSUE TITLE
[ENHANCEMENT]: Add a sample showing how to use `device_view`s to construct a map from existing memory

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cuCollections#282]
### Is your feature request related to a problem? Please describe.

As a user of cuco, there are times where I want to treat existing memory as if it were a `cuco::static_map` or `cuco::static_multimap`. I know the `deview_view` types enable me to do this, but it would be nice to have samples showing how that can be done, ideally both in host code and device code. 

### Describe the solution you'd like

Add samples `static_map/device_view.cu` and `static_multimap/device_view.cu` showing how to use the `device_view` and `device_mutable_view` types to allow me to treat existing memory as if it were a `static_map` or `static_multimap`. 

### Additional context

We should do the same for `static_set` too.

**Comment by PointKernel** [comment]
Completed
