### ISSUE TITLE
[ENHANCEMENT]: static_map insert_and_find() should increment size_ on new insertions.

### ISSUE THREAD

**Issue by mattpulver** [NVIDIA/cuCollections#300]
### Is your feature request related to a problem? Please describe.

It would be useful if static_map<>::device_mutable_view::insert_and_find() incremented static_map::size_ on successful insert.

Otherwise if an application is exclusively inserting values via `insert_and_find()` then `get_size()` always returns 0.

How do we know what size to make the output buffer when calling `retrieve_all()`?

### Describe the solution you'd like

Increment `static_map::size_` on successful insert by `insert_and_find()`.

Or, please describe how to get the accurate size of a `static_map` which inserts data via `insert_and_find()`.

**Comment by PointKernel** [comment]
@mattpulver Thanks for reporting the issue.

There are misalignments of implementations between multimap and map and the multimap [get_size](https://github.com/NVIDIA/cuCollections/blob/dev/include/cuco/detail/static_multimap/static_multimap.inl#L901-L913) would actually check if each slot is empty to compute the total number of filled slots. We are working on a [refactor](https://github.com/NVIDIA/cuCollections/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Refactor+Open+Address+Data+Structures%22) to clean up the whole code base. 

I will put up a PR shortly to update map `get_size` following the same way as multimap.

**Comment by PointKernel** [comment]
@mattpulver PR merged. 

Note you could also write your own kernel to accumulate the number of successful insertions of `insert_and_find`. A reference can be found [here](https://github.com/NVIDIA/cuCollections/blob/ecd39452cd134e42c0d46ce76a1fefea60d254e5/include/cuco/detail/static_map_kernels.cuh#L92-L108)

**Comment by PointKernel** [comment]
@mattpulver Have to revert the latest changes in size computation due to conflicts in downstream projects. Sorry about that. 

Will let you know once the feature is back (should be quick).

**Comment by mattpulver** [comment]
No worries, thanks for the update. We are using the old `warpcore::CountingHashTable` w/ a cooperative group size of 1 to accomplish this for now, so no rush. Rather wait for a clean/stable solution.

**Comment by mattpulver** [comment]
The first resolution to this issue was reverted by #305.

Has this been resolved by another PR? If not, should this issue be re-opened?

**Comment by mattpulver** [comment]
> @mattpulver Have to revert the latest changes in size computation due to conflicts in downstream projects. Sorry about that.
> 
> Will let you know once the feature is back (should be quick).

@PointKernel was this resolved?

**Comment by PointKernel** [comment]
Hi @mattpulver 

We are deprecating the old single map (https://github.com/NVIDIA/cuCollections/pull/409) and the problem should be fixed in the new implementation.
