### ISSUE TITLE
Switch to cuda::stream_ref

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#331]
`cuco::stream_ref` is a WAR and should be replaced with `cuda::stream_ref`.

`cuda::stream_ref` will be available in libcu++ v2.1.0, and we should get that version soon: rapidsai/rapids-cmake#399.

_Originally posted by @sleeepyjack in https://github.com/NVIDIA/cuCollections/issues/296#issuecomment-1522065120_

**Comment by PointKernel** [comment]
Updates: this is still an experimental feature that requires to define `LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE`  https://godbolt.org/z/jfWsjarTz

**Comment by miscco** [comment]
> Updates: this is still an experimental feature that requires to define `LIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE` https://godbolt.org/z/jfWsjarTz

We will most definitely drop the experimental state for `cuda::stream_ref``in the immediate future

Anything within `<memory_resource>` will stay experimental for a bit longer
