### ISSUE TITLE
[BUG] A few simple issues with static_map

### ISSUE THREAD

**Issue by ChuckHastings** [NVIDIA/cuCollections#41]
Trying to use coco::static_map in cugraph, I found several little issues:

1. device_view::find returns an iterator.  It would be nice to have a const version that returned a const_iterator so the function can be used in a const context
1. Check the visibility of the methods on device_view_base, some things seem to be protected that should probably be public.  In particular, I need to be able to iterate over the slots.  The begin iterator is protected (therefore not visible to the outside), while the end iterator is public.  They should either both be protected and a mechanism in the derived class uses them, or they should both be public (I suspect the latter).
1. The example in the static_map doxygen comments indicates you should create a thrust::pair.  However, pair_atomic_type is set to coco::pair.

**Comment by jrhemstad** [comment]
2. is fixed by https://github.com/NVIDIA/cuCollections/pull/42

**Comment by PointKernel** [comment]
Problems solved in the new design.
