### ISSUE TITLE
Divide by cooperative group size?

### ISSUE THREAD

**Issue by kevkrist** [NVIDIA/cuCollections#423]
https://github.com/NVIDIA/cuCollections/blob/f2af32161959d8b9057cb42458d3af263e467128/examples/static_set/device_ref_example.cu#L60

It looks like the index here is thread-granular, when it should be thread-group granular (as in the insert kernel), unless I'm misunderstanding something. At any rate, it looks like the found iterator is storing redundantly the output of a single contains operation across indices spanning the threads in the cooperative group.

**Comment by PointKernel** [comment]
@kevkrist Good catch!

Will put up a PR to fix this. Thanks!
