### ISSUE TITLE
[BUG]: `<cuda/atomic>` header should be included only in device compilation mode.

### ISSUE THREAD

**Issue by mfbalin** [NVIDIA/cuCollections#449]
### Is this a duplicate?

- [X] I confirmed there appear to be no duplicate issues for this bug (https://github.com/NVIDIA/cuCollections/issues)

### Type of Bug

Compile-time Error

### Describe the bug

I want to use cuCollections when compiling for old and new CUDA architectures (sm_35 to sm_90). However, in this case, the minimum cuda architecture is sm_35 and importing `cuda/atomic` header gives an error.

https://github.com/NVIDIA/cuCollections/blob/2101cb31d0210b609cd02c88f9b538e10881d91d/include/cuco/detail/open_addressing/kernels.cuh#L22

If there is a way, this include should be performed only in device mode and when compiling for suitable cuda architectures. Otherwise, one can't use cuco::static_map in the host code. I want to dispatch to different kernels depending on the compute capability of the device. Ideally, without limiting which architectures I am providing support for (>=35).

### How to Reproduce

1. Compile for old and new architectures.
2. Include `cuco/static_map.cuh` header.

### Expected behavior

The host code should be compilable for any CUDA architecture.

**Comment by jrhemstad** [comment]
Hey @mfbalin this is a known issue and something high on my list of things I'd like to address in CCCL in the coming months. See https://github.com/NVIDIA/cccl/issues/1083 for tracking this effort.

**Comment by mfbalin** [comment]
Can I hack `__CUDA_ARCH_LIST__` to remove old architectures from it to compile a specific file as a workaround?

**Comment by mfbalin** [comment]
I want to compile the whole project with 35, 50, ..., 90 but only one file including cuco with 70, ..., 90.

**Comment by jrhemstad** [comment]
> I want to compile the whole project with 35, 50, ..., 90 but only one file including cuco with 70, ..., 90.

Are you using CMake? You should be able to specify per-target properties for a specific file like this:

```
cmake_minimum_required(VERSION 3.18)
project(cuda_arch_example LANGUAGES CUDA)

# Add your library
add_library(my_cuda_library main.cu other.cu)

# Set the default CUDA architecture for the target
set_target_properties(my_cuda_library PROPERTIES CUDA_ARCHITECTURES "35")

# Specify a different CUDA architecture for a specific file
set_source_files_properties(other.cu PROPERTIES CUDA_ARCHITECTURES "72")
```

**Comment by mfbalin** [comment]
> > I want to compile the whole project with 35, 50, ..., 90 but only one file including cuco with 70, ..., 90.
> 
> Are you using CMake? You should be able to specify per-target properties for a specific file like this:
> 
> ```
> cmake_minimum_required(VERSION 3.18)
> project(cuda_arch_example LANGUAGES CUDA)
> 
> # Add your library
> add_library(my_cuda_library main.cu other.cu)
> 
> # Set the default CUDA architecture for the target
> set_target_properties(my_cuda_library PROPERTIES CUDA_ARCHITECTURES "35")
> 
> # Specify a different CUDA architecture for a specific file
> set_source_files_properties(other.cu PROPERTIES CUDA_ARCHITECTURES "72")
> ```

Yes, I am using CMake. This looks promising, let me try it. Thank you!

**Comment by jrhemstad** [comment]
@mfbalin turns out you can't use `CUDA_ARCHITECTURES` on a per-file basis. You'd need to move `other.cu` to a separate object library.

**Comment by mfbalin** [comment]
That works too, so long as there is a way to get it working.

**Comment by mfbalin** [comment]
@jrhemstad Do you know if these separate object libraries can circularly depend on each other?

EDIT: I will figure out a way. Thank you for the pointers!

**Comment by PointKernel** [comment]
Closing as resolved
