### ISSUE TITLE
[BUG] static_map destructor can throw 

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cuCollections#46]
**Describe the bug**

The destructor for `static_map` can throw because it uses [`CUCO_CUDA_TRY` ](https://github.com/NVIDIA/cuCollections/blob/035ed1bdabfbe00f662672c16cb0fd5aca9578a2/include/cuco/detail/static_map.inl#L48-L53)

**Expected behavior**
Shouldn't throw.

**Comment by PointKernel** [comment]
No longer relevant.
