### ISSUE TITLE
[BUG] A few small bugs

### ISSUE THREAD

**Issue by Nicolas-Iskos** [NVIDIA/cuCollections#47]
1. In `static_map_test.cu`, in the section "Keys are all found after inserting many keys", there should be a call to  `cudaDeviceSynchronize()` after the `thrust::for_each` is called.

2. In `static_map.cuh`, `dynamic_map` is declared twice as a friend class on lines 104 and 106.

**Comment by PointKernel** [comment]
> 1. In `static_map_test.cu`, in the section "Keys are all found after inserting many keys", there should be a call to  `cudaDeviceSynchronize()` after the `thrust::for_each` is called.

`thrust::for_each` is synchronous thus manually invoking `cudaDeviceSynchronize()` is not necessary.

> 2. In `static_map.cuh`, `dynamic_map` is declared twice as a friend class on lines 104 and 106.

No longer relevant.
