### ISSUE TITLE
[ENHANCEMENT]: 128bit hash function

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#480]
### Is your feature request related to a problem? Please describe.

`cuco::static_filter` will require a 128bit hash function implementation which we currently don't have in cuco.

### Describe the solution you'd like

cudf has a `murmurhash3_64_128` [implementation](https://github.com/rapidsai/cudf/blob/3481042d5d1a1f511515cf23f36c43620ad6663e/cpp/include/cudf/hashing/detail/murmurhash3_x64_128.cuh) which we can simply copy&paste.

We have to make sure that the hash values produced by our hasher match the reference implementation (both cudf and the original Murmur3 implementation).

### Describe alternatives you've considered

There is also a 128bit implementation of [XXHash](https://github.com/Cyan4973/xxHash), namely `XXH128`.
Unfortunately, it's quite complex AVX code which makes it harder for us to port to the GPU.

**Comment by PointKernel** [comment]
FYI, corresponding cudf unit tests is [here](https://github.com/rapidsai/cudf/blob/branch-24.08/cpp/tests/hashing/murmurhash3_x64_128_test.cpp)

**Comment by PointKernel** [comment]
Closed via #495
