### ISSUE TITLE
[FEATURE]: Add `static_multiset::count_outer` 

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#488]
### Is your feature request related to a problem? Please describe.

`static_multiset` requires an equivalent function to `static_multimap::count_outer`.

### Describe the solution you'd like

After #462 is finished, add a new API `count_outer` and also add a template parameter to the kernel to switch between `count` and `count_outer` behavior.

### Describe alternatives you've considered

Still an open discussion if this is the best approach to tackle this problem but we couldn't come up with a better solution so far.

**Comment by PointKernel** [comment]
Similar to `retrieve_outer`, this API is probably cudf-specific and should take probe hash and probe key equal as arguments.

**Comment by PointKernel** [comment]
Closed by #490
