### ISSUE TITLE
[FEATURE]: Add `static_multiset::retrieve_outer` 

### ISSUE THREAD

**Issue by sleeepyjack** [NVIDIA/cuCollections#489]
### Is your feature request related to a problem? Please describe.

`static_multiset` requires an equivalent function to `static_multimap::retrieve_outer`.

### Describe the solution you'd like

After #465 is finished, add a new API `retrieve_outer` and also add a template parameter to the kernel to switch between `retrieve` and `retrieve_outer` behavior.

### Describe alternatives you've considered

Still an open discussion if this is the best approach to tackle this problem but we couldn't come up with a better solution so far.

**Comment by PointKernel** [comment]
This API is code-specific and should take probe hash and probe key equal as arguments.
