### ISSUE TITLE
[ENHANCEMENT]: Add `NumInputs` axis to all benchmarks with value `default::N`

### ISSUE THREAD

**Issue by GregoryKimball** [NVIDIA/cuCollections#561]
### Is your feature request related to a problem? Please describe.

It can be useful to sweep the item count when studying cuco benchmarks. I recommend adding an nvbench axis for `NumInputs` to each benchmarks where the axis could make sense. We should set the axis to only run the default value, so as to not change the benchmark runtime or default behavior. Adding the axis allows us to vary each benchmark at runtime.

### Describe the solution you'd like

I believe adding this line and updating the benchmarks to use `NumInputs` would suffice.
`.add_int64_axis("NumInputs", defaults::N);`

### Describe alternatives you've considered

Edit the cuco benchmarks and rebuild

### Additional context

It might also be useful to add placeholder axes for `OCCUPANCY`, `MULTIPLICITY` and `MATCHING_RATE` that set to the default values. Perhaps like: 
```
  .add_float64_axis("Occupancy", defaults::OCCUPANCY);
  .add_float64_axis("MatchingRate", defaults::MATCHING_RATE);
```

**Comment by PointKernel** [comment]
Thanks @GregoryKimball .

We probably want to expose all default parameters as nvbench axis to simplify runtime customization and improve results' readability.

**Comment by sleeepyjack** [comment]
> We probably want to expose all default parameters as nvbench axis to simplify runtime customization and improve results' readability.

Agreed. I can pick this task up tomorrow.

**Comment by sleeepyjack** [comment]
As an extension (probably a later PR) we should also expose axes for compile time tuning parameters such as `CGSize`, `ProbingScheme` and `WindowSize`.

Benchmarking multiple values for each axis will probably lead to combinatorial explosion. We could just specify the default value for each axis. Users will still be able to test different values with the nvbench cli.
