### ISSUE TITLE
[FEATURE]: Expose `hash_function` member function for hash tables

### ISSUE THREAD

**Issue by PointKernel** [NVIDIA/cuCollections#582]
### Is your feature request related to a problem? Please describe.

The current cuco hash tables don't have `hash_function` as a member function because we didn't come up with a proper solution for double hashing, i.e., the underlying hash table may utilize more than one hash function so the below interface doesn't seem to be right:
```cpp
hasher hash_function () const { ... }
```

### Describe the solution you'd like

However, the original idea is not bad and we could use `cuda::std::pair<Hash1, Hash2>` to define `hasher` in the case of double hashing:

```cuda
class static_map {
  ...
  using hasher = cuda::std::conditional_t<is_double_hashing<probing_scheme_type>::value,
    cuda::std::pair<probing_scheme_type::Hash1, probing_scheme_type::Hash2>,
    probing_scheme_type::Hash>;

  ...
  hasher constexpr hash_function () const {
    return cuda::std::pair{probing_scheme.hash_function()};
  }
};
```

In the future, we can also switch to `cuda::std::tuple` if more than two hashers are needed.

### Additional context

We need a build-time `is_double_hashing` trait to implement this.

**Comment by sleeepyjack** [comment]
> In the future, we can also switch to cuda::std::tuple if more than two hashers are needed.

I would go with `cuda::std::tuple` from the start. The only difference is that `pair` provides `.first` and `.second` members. A tuple is more generic and requires no future code change.

**Comment by sleeepyjack** [comment]
Shall we move this logic to the `probing_scheme` class? `double_hashing::hasher` would define `tuple<Hash1, Hash2>` while the other probing scheme types would just use `Hash`. From there: `auto static_map::hash_function() { probing_scheme_.hash_function(); }`

**Comment by PointKernel** [comment]
> Shall we move this logic to the `probing_scheme` class? `double_hashing::hasher` would define `tuple<Hash1, Hash2>` while the other probing scheme types would just use `Hash`. From there: `auto static_map::hash_function() { probing_scheme_.hash_function(); }`

Yes, that's what I have in mind as well
