### ISSUE TITLE
[BUG]: nvrtc Excessive error pragma for --expt-relaxed-constexpr

### ISSUE THREAD

**Issue by kroburg** [NVIDIA/cuCollections#594]
### Is this a duplicate?

- [x] I confirmed there appear to be no duplicate issues for this bug (https://github.com/NVIDIA/cuCollections/issues)

### Type of Bug

Compile-time Error

### Describe the bug

Hello.

I'm trying to use cuco with nvrtc. And it fails with error
```
catastrophic error: #error directive: "Support for relaxed constexpr is required (nvcc flag --expt-relaxed-constexpr)"
  #error "Support for relaxed constexpr is required (nvcc flag --expt-relaxed-constexpr)"
```

Please consider [thread](https://github.com/NVIDIA/jitify/issues/30) from jitify. Looks like it is not required for nvrtc.

I'm not sure if I can have success with nvrtc anyway.
I have to include cuco/static_map.cuh to compose static_map_ref for kernel params like that: `decltype(((const map_t*)nullptr)->ref(cuco::find));`
This is because I don't known how to craft StorageRef template argument.

From my expirience including such a "wide" header as cuco/static_map.cuh will not work with nvrtc because of host api calls.

### How to Reproduce

NA

### Expected behavior

cuco compiles using nvrtc.

### NVCC version

NA

**Comment by kroburg** [comment]
Well, I got it. It will not work anyway :-/

```
/tmp/sis_cuda_package.tmp.0caa4e15e025276df64cd21d90ac80e4/cccl/thrust/thrust/detail/execute_with_dependencies.h(63): error: A function explicitly marked as a __host__ function is not allowed in JIT mode
    _CCCL_HOST execute_with_dependencies(super_t const& super, Dependencies&&... deps)
```
               ^

**Comment by PointKernel** [comment]
#595 improves the situation by disabling the relaxed constexpr requirements in cuco

**Comment by kroburg** [comment]
Great! Thank you.

**Comment by PointKernel** [comment]
Closing as resolved
