### ISSUE TITLE
[FEA] `dynamic_multimap` 

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cuCollections#60]
**Is your feature request related to a problem? Please describe.**

`dynamic_map` only allows a single instance of each key. 

**Describe the solution you'd like**

I would like an extension of `dynamic_map` that supports multiple instances of each key. 

**Additional context**

Related: https://github.com/NVIDIA/cuCollections/issues/59

**Comment by PointKernel** [comment]
Closing this as the feature is no longer needed.


Feel free to reopen this issue when appropriate.
