### ISSUE TITLE
[BUG] Add examples for  static_map device APIs and dynamic_map APIs

### ISSUE THREAD

**Issue by seunghwak** [NVIDIA/cuCollections#61]
**Describe the bug**
Links are broken in https://github.com/NVIDIA/cuCollections#static_map ("as well as device APIs for individual operations (example).") and https://github.com/NVIDIA/cuCollections#dynamic_map ("It currently only provides host, bulk APIs (example).").

**Steps/Code to reproduce bug**
Click "example" and you will see 404 This is not the page you are looking for.

**Expected behavior**
Show the example pages.

**Comment by jrhemstad** [comment]
Yeah, those are stubs because the examples don't exist yet :)

**Comment by jrhemstad** [comment]
I updated the links to reflect that they are TODO.

**Comment by PointKernel** [comment]
No longer relevant
