### ISSUE TITLE
[BUG] Make __cuda_memcmp an inline function

### ISSUE THREAD

**Issue by ChuckHastings** [NVIDIA/cuCollections#64]
If I include <cuco/static_map.cuh> in multiple .cu files I get multiple definitions of the function __cuda_memcmp in my library.

**Comment by griwes** [comment]
This was a libcu++ bug fixed in CUDA 11.0 I believe.

**Comment by ChuckHastings** [comment]
I think the issue is that the function is not defined as an inline function.  If I add the `inline` keyword at the beginning of line 2 of the file `cuda_memcmp.cuh` it works fine.

**Comment by griwes** [comment]
Oh. Looks like this project has its own copy of that function. Very well, disregard my previous comment ;)

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cuCollections/pull/67
