### ISSUE TITLE
[FEA] CUDA stream support

### ISSUE THREAD

**Issue by seunghwak** [NVIDIA/cuCollections#65]
**Is your feature request related to a problem? Please describe.**
static_map/dynamic_map currently does not take cudaStream_t stream parameter. This often requires additional synchronization and limits speedup we can get when we wish to concurrently run multiple cuCollection operations using multiple CUDA streams.

**Describe the solution you'd like**
Add CUDA stream support

**Additional context**
cuGraph needs this to run multiple graph kernels concurrently using multiple CUDA streams (for batch processing).

**Comment by chirayuG-nvidia** [comment]
Stream support for static_map added in commit https://github.com/NVIDIA/cuCollections/commit/76a6ba1d08761f7e14f27c6794ca2d469301b54f

**Comment by PointKernel** [comment]
Completed.

All new cuco hash tables take a stream parameter.
