### ISSUE TITLE
[DOC] It is unclear whether find operation supports in-place mode or not

### ISSUE THREAD

**Issue by seunghwak** [NVIDIA/cuCollections#66]
## Report needed documentation

**Report needed documentation**
https://github.com/NVIDIA/cuCollections/blob/dev/include/cuco/static_map.cuh#L201
This documentation doesn't say whether ```InputIt first``` and ```OutputIt output_begin``` can coincide or not. It seems like this is supported based on the current implementation, but I am not sure the API intends to support this in the future or not.

**Describe the documentation you'd like**
Explicitly say whether this is supported or not.

For example, thrust is explicit about whether in-place operation is supported or not.

thrust::transform
https://thrust.github.io/doc/group__transformations_gacbd546527729f24f27dc44e34a5b8f73.html
```The input and output sequences may coincide, resulting in an in-place transformation```

thrust::reduce_by_key
https://thrust.github.io/doc/group__reductions_gad5623f203f9b3fdcab72481c3913f0e0.html#gad5623f203f9b3fdcab72481c3913f0e0
```The input ranges shall not overlap either output range.```

**Comment by PointKernel** [comment]
The find operation expects an input of the key type and produces an output of the mapped (or payload) type. While find supports an in-place transformation when the key type and payload type are the same, this practice is discouraged as the key and payload types are not semantically guaranteed to be identical.
