### ISSUE TITLE
[FEA] Replace thrust/cuco::pair with libcu++ tuple/pair

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cuCollections#69]
**Is your feature request related to a problem? Please describe.**

cuco currently uses a combination of Thrust and a custom pair type.

**Describe the solution you'd like**

We should just use everything from libcu++ for pair/tuple.

**Comment by jrhemstad** [comment]
I'm not sure if we actually want to do this anymore. Having control over the slot storage type has been very handy.

**Comment by PointKernel** [comment]
> Having control over the slot storage type has been very handy.

@jrhemstad  Can you be more specific? We can control storage type with `cuda::pair` also and `cuda::pair` seems aligned by default.

**Comment by PointKernel** [comment]
I believe this feature request is no longer desired. Feel free to reopen if needed
