### ISSUE TITLE
[BUG] Find does not return the empty sentinel value for missing or empty sentinel keys

### ISSUE THREAD

**Issue by seunghwak** [NVIDIA/cuCollections#74]
**Describe the bug**
https://github.com/NVIDIA/cuCollections/blob/2196040f0562a0280292eebef5295d914f615e63/include/cuco/static_map.cuh#L192

states "Else, copies the empty value sentinel". However, for missing keys, it seems like garbage values are returned.

**Steps/Code to reproduce bug**
https://github.com/NVIDIA/cuCollections/blob/2196040f0562a0280292eebef5295d914f615e63/include/cuco/detail/static_map_kernels.cuh#L276

If ```found``` is ```view.end()```, ```found->second.load(cuda::std::memory_order_relaxed)``` loads from slots[capacity] and this access is out-of-bound if the number of allocated slots is capacity.

I think this should be

```found == view.end() ? view.get_empty_value_sentinel() : found->second.load(cuda::std::memory_order_relaxed)```
or
we need to allocate capacity + 1 slots and store the empty sentinel (key, value) pairs in the last slot.

**Comment by jrhemstad** [comment]
> found == view.end() ? view.get_empty_value_sentinel() : found->second.load(cuda::std::memory_order_relaxed)

Yeah, this looks like a sane fix to me.
